# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Resonant Converter 2023
author: Nicola ZAUPA
logo: 'logo2.png'
description: >-
  This book presents the work done for controlling resonant converters with a hybrid approach.


# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

parse:
  myst_enable_extensions:
  - html_admonition
  - dollarmath
  - amsmath
  - replacements
#     # don't forget to list any other extensions you want enabled,
#     # including those that are enabled by default!
#     - amsmath
#     - siunitx
#     - amssymb
#   myst_dmath_double_inline: true


# Define the name of the latex output file for PDF builds
latex:
  latex_engine: pdflatex
  latex_documents:
    targetname: book.tex

html:
  favicon                     : 'qe-logo-large.png'
  # home_page_in_navbar         : false
  # use_edit_page_button        : true
  # use_repository_button       : true
  # use_issue_button            : true


# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

sphinx:
  config:
    bibtex_reference_style: author_year

# Information about where the book exists on the web
repository:
  url: https://github.com/nzaupa/FPGA_resonant_converter  # Online location of your book
  path_to_book: docs  # Optional path to your book, relative to the repository root
  branch: master  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  favicon: 'logo2.png'
  # home_page_in_navbar         : false
  # use_edit_page_button        : true
  use_issues_button: false
  use_repository_button: true